//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.09 at 06:23:24 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "prodInfoService.soap.lfm.rdlabsrl.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rdlabsrl.lfm.soap.prodinfoservice;
